### ISSUE TITLE
Crafting project.json question

### ISSUE THREAD

**Issue by JensNordenbro** [stevedesmond-ca/dotnet-arm#2]
Hi! We are using your repo as inspiration creating a Yocto build of dotnet-cli !

However when trying out dotnet.exe, the system complained about the project targeting another framework: 

> The specified framework 'Microsoft.NETCore.App', version '2.0.0-beta-001581-00'
> was not found.
>   - Check application dependencies and target a framework version installed at:
>       C:\Program Files\dotnet\shared\Microsoft.NETCore.App\
>   - The following versions are installed:
>       1.0.1
>       1.1.0
>   - Alternatively, install the framework version '2.0.0-beta-001581-00'.
> 

So, I created a new, minimal project "dotnet new -t web" and tried running it on my pc using daily build on  Windows x64. The results were the same.
Changing project json to:

 "dependencies": {
    "Microsoft.NETCore.App": {
      "version": "**2.0.0-beta-001581-00**",
      "type": "platform"
    },

...

 "frameworks": {
    "**netcoreapp2.0**": {
      "imports": [
        "dotnet5.6",
        "dnxcore50",
        "portable-net45+win8"
      ]
    }

and adding a NuGet.config with the following feed:

> "https://dotnet.myget.org/F/dotnet-core/api/v3/index.json"

...resulted in me being able to start the application; however an exception occurs immediately: 

> Unhandled Exception: System.IO.FileLoadException: Could not load file or assembl
> y 'System.Threading.Overlapped, Version=4.1.0.0, Culture=neutral, PublicKeyToken
> =b03f5f7f11d50a3a'. The located assembly's manifest definition does not match th
> e assembly reference. (Exception from HRESULT: 0x80131040)
> 

Using IL-spy I manage to find and introspect this assembly 

> // C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.0-beta-001581-00\System.Threading.Overlapped.dll
> // System.Threading.Overlapped, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
> 
> // Global type: <Module>
> // Architecture: x64
> // This assembly contains unmanaged code.
> // Runtime: .NET 4.0
> 

**Do you have any suggestions that can point me in the right direction I would be grateful!** 

> Complete project,.json: 
> {
>   "userSecretsId": "aspnet-WebApplication-0799fe3e-6eaf-4c5f-b40e-7c6bfd5dfa9a",
> 
>   "dependencies": {
>     "Microsoft.NETCore.App": {
>       "version": "2.0.0-beta-001581-00",
>       "type": "platform"
>     },
>     "Microsoft.AspNetCore.Authentication.Cookies": "1.0.0",
>     "Microsoft.AspNetCore.Diagnostics": "1.0.0",
>     "Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore": "1.0.0",
>     "Microsoft.AspNetCore.Identity.EntityFrameworkCore": "1.0.0",
>     "Microsoft.AspNetCore.Mvc": "1.0.1",
>     "Microsoft.AspNetCore.Razor.Tools": {
>       "version": "1.0.0-preview2-final",
>       "type": "build"
>     },
>     "Microsoft.AspNetCore.Routing": "1.0.1",
>     "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",
>     "Microsoft.AspNetCore.Server.Kestrel": "1.0.1",
>     "Microsoft.AspNetCore.StaticFiles": "1.0.0",
>     "Microsoft.EntityFrameworkCore.Sqlite": "1.0.1",
>     "Microsoft.EntityFrameworkCore.Tools": {
>       "version": "1.0.0-preview2-final",
>       "type": "build"
>     },
>     "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0",
>     "Microsoft.Extensions.Configuration.Json": "1.0.0",
>     "Microsoft.Extensions.Configuration.UserSecrets": "1.0.0",
>     "Microsoft.Extensions.Logging": "1.0.0",
>     "Microsoft.Extensions.Logging.Console": "1.0.0",
>     "Microsoft.Extensions.Logging.Debug": "1.0.0",
>     "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0",
>     "Microsoft.VisualStudio.Web.CodeGeneration.Tools": {
>       "version": "1.0.0-preview2-update1",
>       "type": "build"
>     },
>     "Microsoft.VisualStudio.Web.CodeGenerators.Mvc": {
>       "version": "1.0.0-preview2-update1",
>       "type": "build"
>     }
>   },
> 
>   "tools": {
>     "Microsoft.AspNetCore.Razor.Tools": {
>       "version": "1.0.0-preview2-final",
>       "imports": "portable-net45+win8+dnxcore50"
>     },
>     "Microsoft.AspNetCore.Server.IISIntegration.Tools": {
>       "version": "1.0.0-preview2-final",
>       "imports": "portable-net45+win8+dnxcore50"
>     },
>     "Microsoft.EntityFrameworkCore.Tools": {
>       "version": "1.0.0-preview2-final",
>       "imports": [
>         "portable-net45+win8+dnxcore50",
>         "portable-net45+win8"
>       ]
>     },
>     "Microsoft.Extensions.SecretManager.Tools": {
>       "version": "1.0.0-preview2-final",
>       "imports": "portable-net45+win8+dnxcore50"
>     },
>     "Microsoft.VisualStudio.Web.CodeGeneration.Tools": {
>       "version": "1.0.0-preview2-final",
>       "imports": [
>         "portable-net45+win8+dnxcore50",
>         "portable-net45+win8"
>       ]
>     }
>   },
> 
>   "frameworks": {
>     "netcoreapp2.0": {
>       "imports": [
>         "dotnet5.6",
>         "dnxcore50",
>         "portable-net45+win8"
>       ]
>     }
>   },
> 
>   "buildOptions": {
>     "debugType": "portable",
>     "emitEntryPoint": true,
>     "preserveCompilationContext": true
>   },
> 
>   "runtimeOptions": {
>     "configProperties": {
>       "System.GC.Server": true
>     }
>   },
> 
>   "publishOptions": {
>     "include": [
>       "wwwroot",
>       "**/*.cshtml",
>       "appsettings.json",
>       "web.config"
>     ]
>   },
> 
>   "scripts": {
>     "prepublish": [ "npm install", "bower install", "gulp clean", "gulp min" ],
>     "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
>   },
> 
>   "tooling": {
>     "defaultNamespace": "WebApplication"
>   }
> }
>

**Comment by SteveDesmond-ca** [comment]
If you're not building it yourself, you'll need to grab the latest shared
framework from https://GitHub.com/dotnet/core-setup

On Feb 16, 2017 9:56 AM, "JensNordenbro" <notifications@github.com> wrote:

Hi! We are using your repo as inspiration creating a Yocto build of
dotnet-cli !

However when trying out dotnet.exe, the system complained about the project
targeting another framework:

The specified framework 'Microsoft.NETCore.App', version
'2.0.0-beta-001581-00'
was not found.

   - Check application dependencies and target a framework version
   installed at:
   C:\Program Files\dotnet\shared\Microsoft.NETCore.App\
   - The following versions are installed:
   1.0.1
   1.1.0
   - Alternatively, install the framework version '2.0.0-beta-001581-00'.

So, I created a new, minimal project "dotnet new -t web" and tried running
it on my pc using daily build on Windows x64. The results were the same.
Changing project json to:

"dependencies": {
"Microsoft.NETCore.App": {
"version": "*2.0.0-beta-001581-00*",
"type": "platform"
},

...

"frameworks": {
"*netcoreapp2.0*": {
"imports": [
"dotnet5.6",
"dnxcore50",
"portable-net45+win8"
]
}

and adding a NuGet.config with the following feed:

"https://dotnet.myget.org/F/dotnet-core/api/v3/index.json"

...resulted in me being able to start the application; however an exception
occurs immediately:

Unhandled Exception: System.IO.FileLoadException: Could not load file or
assembl
y 'System.Threading.Overlapped, Version=4.1.0.0, Culture=neutral,
PublicKeyToken
=b03f5f7f11d50a3a'. The located assembly's manifest definition does not
match th
e assembly reference. (Exception from HRESULT: 0x80131040)

Using IL-spy I manage to find and introspect this assembly

// C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.0-beta-001581-
00\System.Threading.Overlapped.dll
// System.Threading.Overlapped, Version=4.1.0.0, Culture=neutral,
PublicKeyToken=b03f5f7f11d50a3a

// Global type:
// Architecture: x64
// This assembly contains unmanaged code.
// Runtime: .NET 4.0

*Do you have any suggestions that can point me in the right direction I
would be grateful!*

Complete project,.json:
{
"userSecretsId": "aspnet-WebApplication-0799fe3e-6eaf-4c5f-b40e-
7c6bfd5dfa9a",

"dependencies": {
"Microsoft.NETCore.App": {
"version": "2.0.0-beta-001581-00",
"type": "platform"
},
"Microsoft.AspNetCore.Authentication.Cookies": "1.0.0",
"Microsoft.AspNetCore.Diagnostics": "1.0.0",
"Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore": "1.0.0",
"Microsoft.AspNetCore.Identity.EntityFrameworkCore": "1.0.0",
"Microsoft.AspNetCore.Mvc": "1.0.1",
"Microsoft.AspNetCore.Razor.Tools": {
"version": "1.0.0-preview2-final",
"type": "build"
},
"Microsoft.AspNetCore.Routing": "1.0.1",
"Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",
"Microsoft.AspNetCore.Server.Kestrel": "1.0.1",
"Microsoft.AspNetCore.StaticFiles": "1.0.0",
"Microsoft.EntityFrameworkCore.Sqlite": "1.0.1",
"Microsoft.EntityFrameworkCore.Tools": {
"version": "1.0.0-preview2-final",
"type": "build"
},
"Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0",
"Microsoft.Extensions.Configuration.Json": "1.0.0",
"Microsoft.Extensions.Configuration.UserSecrets": "1.0.0",
"Microsoft.Extensions.Logging": "1.0.0",
"Microsoft.Extensions.Logging.Console": "1.0.0",
"Microsoft.Extensions.Logging.Debug": "1.0.0",
"Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0",
"Microsoft.VisualStudio.Web.CodeGeneration.Tools": {
"version": "1.0.0-preview2-update1",
"type": "build"
},
"Microsoft.VisualStudio.Web.CodeGenerators.Mvc": {
"version": "1.0.0-preview2-update1",
"type": "build"
}
},

"tools": {
"Microsoft.AspNetCore.Razor.Tools": {
"version": "1.0.0-preview2-final",
"imports": "portable-net45+win8+dnxcore50"
},
"Microsoft.AspNetCore.Server.IISIntegration.Tools": {
"version": "1.0.0-preview2-final",
"imports": "portable-net45+win8+dnxcore50"
},
"Microsoft.EntityFrameworkCore.Tools": {
"version": "1.0.0-preview2-final",
"imports": [
"portable-net45+win8+dnxcore50",
"portable-net45+win8"
]
},
"Microsoft.Extensions.SecretManager.Tools": {
"version": "1.0.0-preview2-final",
"imports": "portable-net45+win8+dnxcore50"
},
"Microsoft.VisualStudio.Web.CodeGeneration.Tools": {
"version": "1.0.0-preview2-final",
"imports": [
"portable-net45+win8+dnxcore50",
"portable-net45+win8"
]
}
},

"frameworks": {
"netcoreapp2.0": {
"imports": [
"dotnet5.6",
"dnxcore50",
"portable-net45+win8"
]
}
},

"buildOptions": {
"debugType": "portable",
"emitEntryPoint": true,
"preserveCompilationContext": true
},

"runtimeOptions": {
"configProperties": {
"System.GC.Server": true
}
},

"publishOptions": {
"include": [
"wwwroot",
"**/*.cshtml",
"appsettings.json",
"web.config"
]
},

"scripts": {
"prepublish": [ "npm install", "bower install", "gulp clean", "gulp min" ],
"postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath%
--framework %publish:FullTargetFramework%" ]
},

"tooling": {
"defaultNamespace": "WebApplication"
}
}

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/stevedesmond-ca/dotnet-arm/issues/2>, or mute the thread

**Comment by JensNordenbro** [comment]
Hi, I did...I think.. "So, I created a new, minimal project "dotnet new -t web" and tried running
it on my pc using **daily build on Windows x64**. "
I grabbed  https://dotnetcli.blob.core.windows.net/dotnet/master/Installers/Latest/dotnet-win-x64.latest.exe 
Or is there something else needed?

**Comment by SteveDesmond-ca** [comment]
Are you building CLI off of master, or rel/1.0.0? I hit a similar issue on
1.0.0 and switching to master fixed it since the ref assemblies are
different between major versions.

**Comment by gitchomik** [comment]
@JensNordenbro: I have same problem, my solution was
- use dotnet nightly builds using docker (docker run -it --rm microsoft/dotnet-nightly:2.0.0-beta-sdk
i use dotnet version **2.0.0-beta-001507-00**)
- migrate from .json to .csproj
- build everything on docker
- run on version https://github.com/stevedesmond-ca/dotnet-arm/releases/tag/2.0.0-beta-001507-00

**Comment by JensNordenbro** [comment]
@stevedesmond-ca : We build CLI off of master. However since I have not been able to run a 2.0.0-beta using PC only (Windows x64, daily build) I havn't continued to the ARM-build on the board. 
I could try switching to Linux,Docker as @gitchomik said to close the gap between Windows and Linux. Did you use the .csproj-tooling @stevedesmond-ca ?

**Comment by SteveDesmond-ca** [comment]
Yeah, right now pretty much everything requires x64 as the build host.

**Comment by JensNordenbro** [comment]
Ok, thank you @stevedesmond-ca  and @gitchomik ! 
Just confirmed that also changing to csproj-tooling made everything work!

**Comment by SteveDesmond-ca** [comment]
Good to know 2.0 drops project.json support!
